FROM ubuntu:latest

EXPOSE 8080
COPY Crossfit-Dashboard /Webapp
#COPY dist /Webapp
#COPY assets /Webapp
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
#RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install http-server -g
WORKDIR /usr/apps/Webapp/
CMD ["http-server", "-c-1", "/Webapp"]